
spring:
  cloud:
    euruka:
      connect-string: localhost:8761

zuul:
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    user-service:
       serviceId: user-servcie

    bank-service:
       serviceId: bank-service
       
    statistic-service:
       serviceId: statistic-service


server:
  port: 8080
